-- You can use this file to load seed data into the database using SQL statements
insert into Member (id, name, email, phone_number) values (0, 'John Smith', 'john.smith@mailinator.com', '2125551212') 

-- insert pessoas
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(1, '860.518.214-81', 'JOAO BAURETE', 0);
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(2, '637.456.259-35', 'TIAO BAURETE', 0);
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(3,'377.914.546-45', 'MARISA BAURETE', 0);
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(4, '760.318.274-91', 'CARLOS BAURETE', 0);
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(5, '537.156.289-25', 'JACOBIS BAURETE', 0);
INSERT INTO TB_PESSOA (ID, CPF, NOME, VERSAO) VALUES(6, '277.314.526-05', 'JIM BAURETE', 0);

-- insert alunos
INSERT INTO TB_ALUNO (DATA_ANIVERSARIO, MATRICULA, ID) VALUES('1990-05-09', '11213643', 1);
INSERT INTO TB_ALUNO (DATA_ANIVERSARIO, MATRICULA, ID) VALUES('1993-12-15', '11213645', 2);
INSERT INTO TB_ALUNO (DATA_ANIVERSARIO, MATRICULA, ID) VALUES('1991-08-21', '11213647', 3);

-- insert professores
INSERT INTO TB_PROFESSOR (SALARIO, ID) VALUES (10252.22, 4);
INSERT INTO TB_PROFESSOR (SALARIO, ID) VALUES (9252.73, 5);
INSERT INTO TB_PROFESSOR (SALARIO, ID) VALUES (6252.20, 6);

--insert salas
INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (2,10,100,"2015-05-30","Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (3,20,101,"2015-06-06","augue. Sed molestie. Sed id risus quis diam luctus lobortis.",0,1,1,1,0);


INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (4,30,102,"2015-05-02","nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (5,40,103,"2015-05-26","lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie.",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (6,50,104,"2015-05-19","odio. Nam interdum enim non nisi. Aenean eget metus. In",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (7,60,105,"2015-05-30","velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (8,70,106,"2015-05-31","urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO)
VALUES (9,80,107,"2015-06-11","magna a neque. Nullam ut nisi a odio semper cursus.",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (10,90,108,"2015-05-29","arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.",0,1,1,1,0);

INSERT INTO TB_SALA (ID,CAPACIDADE,CODIGO,DATATERMINOMANUTENCAO,OBSERVACAO,POSSUICOMPUTADOR,POSSUIDATASHOW,POSSUIQUADROBRANCO,STATUS,VERSAO) 
VALUES (11,100,109,"2015-05-22","porttitor tellus non magna. Nam ligula elit, pretium et, rutrum",0,1,1,1,0);

